all:
	iverilog -o AND C9-3-AND.v C9-3-AND-test.v && ./AND
	iverilog -o OR C9-3-OR.v C9-3-OR-test.v && ./OR
and:
	iverilog -o AND C9-3-AND.v C9-3-AND-test.v && ./AND
or:
	iverilog -o OR C9-3-OR.v C9-3-OR-test.v && ./OR
clean:
	rm -rf AND
	rm -rf OR
